

#         Powered by TabooLib 6.0         #


Database:
  # LOCAL, MONGODB, DISABLE
  method: LOCAL
  url:
    client: 'mongodb://localhost:3307'
    database: test
    collection: adyeshach

Settings:
  debug: false
  # Must be less than "view-distance" in server.properties
  visible-distance: 64
  # JOIN: When player joined the server
  # KEEP_ALIVE: When player sent a first position packet
  spawn-event: KEEP_ALIVE
  # Calculate on the main thread (Very low latency, Otherwise >2000ms)
  pathfinder-sync: true
  # Delete NPC files when the specified world does not exist
  delete-file-in-unknown-world:
    - 'dungeon_world_1'
    - 'dungeon_world_2'
    - 'custom?'
  # Refresh cycle for view conditions
  view-condition-interval: 40