

#         Powered by TabooLib 5.0         #


Language:
  - en_US

Database:
  method: LOCAL
  url:
    client: 'mongodb://localhost:3307'
    database: test
    collection: adyeshach

Settings:
  debug: false
  editor-mode: CHAT
  visible-distance: 64
  pathfinder-proxy: true
  pathfinder-proxy-spawn:
    world:
      x: 0
      z: 0
    world_nether:
      x: 0
      z: 0
    world_the_end: ~bukkit