

#         Powered by TabooLib 5.0         #


Language:
  - en_US

Database:
  method: LOCAL
  url:
    client: 'mongodb://localhost:3307'
    database: test
    collection: adyeshach

Settings:
  debug: false
  editor-mode: CHAT
  visible-distance: 64
  pathfinder-proxy: true
  spawn-event: KEEP_ALIVE