

#         Powered by TabooLib 5.0         #


Language:
  - en_US
  - zh_CN

Database:
  method: LOCAL
  url:
    client: 'mongodb://localhost:3307'
    database: test
    collection: adyeshach

Settings:
  debug: false
  editor-mode: BOOK
  visible-distance: 64