

#         Powered by TabooLib 5.0         #


Language:
  - en_US
  - zh_CN

Database:
  # LOCAL (using taboolib player database), MONGODB (will not support mysql storage)
  method: LOCAL
  url:
    client: 'mongodb://localhost:3307'
    database: test
    collection: adyeshach