

#         Powered by TabooLib 6.0         #


Database:
  # LOCAL, MONGODB
  method: LOCAL
  url:
    client: 'mongodb://localhost:3307'
    database: test
    collection: adyeshach

Settings:
  debug: false
  # Must be less than "view-distance" in server.properties
  visible-distance: 64
  # BOOK: Compatible Version
  # CHAT: Recommended Version (Affected by Iridescent plugin, it will be invalid)
  editor-mode: CHAT
  # JOIN: When player joined the server
  # KEEP_ALIVE: When player sent first position packet
  spawn-event: KEEP_ALIVE
  # Calculate on the main thread (Very low latency, Otherwise >2000ms)
  pathfinder-sync: true
  # Display meta data per line in the editor
  editor-meta-per-line: 3
  # Delete NPC files when the specified world does not exist
  delete-file-in-unknown-world:
    - 'dungeon_world_1'
    - 'dungeon_world_2'
    - 'custom?'